### ISSUE TITLE
Bug: Missing role "roles/storage.objectUser"

### ISSUE THREAD

**Issue by muffl0n** [Cyclenerd/google-cloud-iam#2]
**Describe the bug**
roles/storage.objectUser was added on August, 23rd: https://cloud.google.com/storage/docs/release-notes#August_23_2023

Unfortunately it's missing in `google-cloud-iam`

**Comment by Cyclenerd** [comment]
Added with last run: https://github.com/Cyclenerd/google-cloud-iam/commit/47e3ecbf0718281ea1e0ebb03ce15fe55095155f
